export const PRACTICE_AREA_OPTIONS = [
  "Personal Injury",
  "Workers' Compensation",
  "Mass Tort",
  "Medical Malpractice",
  "Product Liability",
  "Premises Liability",
  "Wrongful Death",
  "Auto Accidents",
  "Truck Accidents",
  "Motorcycle Accidents",
  "Slip and Fall",
  "Catastrophic Injury",
  "Family Law",
  "Divorce",
  "Child Custody",
  "Adoption",
  "Estate Planning",
  "Probate",
  "Business Formation",
  "Commercial Litigation",
  "Employment Law",
  "Wrongful Termination",
  "Wage and Hour",
  "Civil Rights",
  "Immigration",
  "Criminal Defense",
  "DUI Defense",
  "Bankruptcy",
  "Consumer Protection",
  "Construction Defects",
  "Environmental Litigation",
  "Securities Litigation",
  "Intellectual Property",
  "Real Estate",
  "Insurance Bad Faith",
] as const;

export function normalizePracticeArea(value: string) {
  return value.trim();
}
